# Generated by Django 5.2.12 on 2026-07-26 03:16

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('object_id', models.PositiveBigIntegerField()),
                ('face', models.CharField(default='front', max_length=10)),
                ('x', models.DecimalField(decimal_places=4, max_digits=6)),
                ('y', models.DecimalField(decimal_places=4, max_digits=6)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ('consoleporttemplate', 'consoleserverporttemplate', 'powerporttemplate', 'poweroutlettemplate', 'interfacetemplate', 'frontporttemplate', 'rearporttemplate'))), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_visualizer_positions', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'component position',
                'verbose_name_plural': 'component positions',
                'ordering': ('device_type', 'content_type', 'object_id'),
                'indexes': [models.Index(fields=['device_type'], name='netbox_devi_device__a360ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='netbox_deviceportvisualizer_componentposition_unique_component')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
